### PR TITLE
fix(storage::netapp::ontap::restapi): convert latencies to milliseconds

### LINKED ISSUE #5929: [storage::netapp::ontap::restapi::mode::cluster]: latency unit mismatch (µs vs ms)
# Bug report
latency unit mismatch (µs vs ms)

## Quick description
The storage::netapp::ontap::restapi plugin (mode cluster) collects latency values from the NetApp REST API in microseconds (µs) but displays and labels them as milliseconds (ms) without applying a conversion (division by 1000). This results in incorrect performance data and false positive alerts.

## How to reproduce
Environment: Oracle Linux Server release 9.5 (WSL).
Version of the plugin: 20260100 (Commit 59a7acd03).
Information about the monitored resource: NetApp ONTAP Cluster monitored via REST API.

Command line:
perl src/centreon_plugins.pl \
    --plugin=storage::netapp::ontap::restapi::plugin \
    --mode=cluster \
    --hostname='<NETAPP_IP>' \
    --api-username='<USER>' \
    --api-password='<PASSWORD>' \
    --insecure \
    --verbose

## Expected result
The plugin should display the latency in actual milliseconds by dividing the raw API value by 1000. For a healthy cluster, the output should look like: read latency: 0.51 ms, write latency: 0.92 ms

## Actual result
The plugin displays the raw microsecond value with a "ms" suffix: read latency: 517 ms, write latency: 922 ms

##Suggested Fix
The issue is located in src/storage/netapp/ontap/restapi/mode/cluster.pm within the manage_selection subroutine. The latency values should be divided by 1000 before being assigned to the results hash:

# Current code (line ~195):
read_latency  => $cluster->{metric}->{latency}->{read},
write_latency => $cluster->{metric}->{latency}->{write},
other_latency => $cluster->{metric}->{latency}->{other},
total_latency => $cluster->{metric}->{latency}->{total}

# Suggested fix:
read_latency  => $cluster->{metric}->{latency}->{read} / 1000,
write_latency => $cluster->{metric}->{latency}->{write} / 1000,
other_latency => $cluster->{metric}->{latency}->{other} / 1000,
total_latency => $cluster->{metric}->{latency}->{total} / 1000

### PR DESCRIPTION
**Pull request by omercier**
## Description

Fix #5929 

Refs: CTOR-2155

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Functionality enhancement or optimization (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Summary by Aikido
|  Security Issues: 0 |  Quality Issues: 0 |  Resolved Issues: 0 |
| :--- | :--- | :--- |

**⚡ Enhancements**
* Updated metric labels to use milliseconds units for latency metrics

**🐛 Bugfixes**
* Converted latency outputs to milliseconds and formatted with two decimals

**🔧 Refactors**
* Adapted and reformatted robot tests; added latency formatting test cases

**📚 Documentation**
* Updated file header copyright year to 2026-Present for files

<sup>[More info](https://app.aikido.dev/featurebranch/scan/97396511?groupId=59752)</sup>

### CODE REVIEW

File: src/storage/netapp/ontap/restapi/mode/cluster.pm [hunk 1]
```diff
@@ -210,10 +210,10 @@ sub manage_selection {
                 write_iops    => $cluster->{metric}->{iops}->{write},
                 other_iops     => $cluster->{metric}->{iops}->{other},
                 total_iops    => $cluster->{metric}->{iops}->{total},
-                read_latency  => $cluster->{metric}->{latency}->{read},
-                write_latency => $cluster->{metric}->{latency}->{write},
-                other_latency  => $cluster->{metric}->{latency}->{other},
-                total_latency => $cluster->{metric}->{latency}->{total}
+                read_latency  => $cluster->{metric}->{latency}->{read} ? $cluster->{metric}->{latency}->{read} / 1_000 : undef,
```
Comment (scresto31) [inline src/storage/netapp/ontap/restapi/mode/cluster.pm:213]: Just a question: shouldn't these values be displayed using a %.2f format?

Comment (omercier) [reply src/storage/netapp/ontap/restapi/mode/cluster.pm:213]: Done 👍🏻

**Review by scresto31 — APPROVED** [review]
